language: c

os: linux
dist: bionic
arch: amd64

env:
  - MRUBY_CONFIG=travis_config.rb
script: "rake -m && rake test"

deploy:
  provider: releases
  token: ${token}
  file: "build/host/lib/libmruby.a"
  skip_cleanup: true
  on:
    tags: true
