name: Release Builds

on:
  push:
    tags:
      - "*.*.*"

permissions: read-all

jobs:
  Release:
    name: "${{ matrix.os }}"
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      max-parallel: 8
      # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
      matrix:
        include:
          - {os: ubuntu-24.04, name: linux_x86_64}
          - {os: macos-latest, name: darwin_arm64}
          - {os: macos-13, name: darwin_x86_64}
    env:
      MRUBY_CONFIG: custom
      CC: clang
      CXX: clang++
      LD: clang
    steps:
      - name: "Checkout ${{ github.ref_name }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
      - name: Brew install automake
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install automake
      - name: Brew install libtool
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install libtool
      - name: Builds
        run: rake
      - name: Rename
        run: |
          cp build/host/bin/mruby mruby-${{matrix.name}}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          # draft: true
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          # body_path: NEWS
          files: mruby-${{matrix.name}}
      - name: Release mrake
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        uses: softprops/action-gh-release@v2
        with:
          files: build/host/bin/mrake
